# Generated by Django 4.0.4 on 2022-05-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=41, unique=True)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
